### ISSUE TITLE
OpenShift AI 2.11 update

### ISSUE THREAD

**Issue by mamurak** [cloud-native-robotz-hackathon/infrastructure#61]
Make hackathon compatible with OpenShift 2.11 (current latest). The main work is in migrating pipelines from KFP v1 (RHOAI 2.8-) to KFP v2 (RHOAI 2.9+).

**Comment by rbo** [comment]
This will be part of #31 - I will close the issue. We initial had 2.10/2.11 running and downgraded to an older version because of #31.

Thank you, @mamurak, for your contribution!
