### ISSUE TITLE
Authentication error when trying to pull the model image from DC image registry

### ISSUE THREAD

**Issue by nexus-Six** [cloud-native-robotz-hackathon/infrastructure#67]
When updating the deployment.yml for the model deployment on the robot, microshift/crio is trying to pull the image from the OCP Image Registry (e.g. default-route-openshift-image-registry.apps.cluster-xxx.com/team-1-ai/model-container:latest) but gets an unauthorized error.  Pulling the app image works.

 
![2024-09-04_17-40](https://github.com/user-attachments/assets/033a4c05-f9ef-4aa8-b924-36f6ff946bfe)

**Comment by rbo** [comment]
We need this : datacenter/per-user/dev/templates/rolebinding-public-pull.yaml

For ai as well.

**Comment by rbo** [comment]
> We need this : datacenter/per-user/dev/templates/rolebinding-public-pull.yaml
> 
> For ai as well.
> 
> 

Here the commit https://github.com/cloud-native-robotz-hackathon/infrastructure/commit/7f3569270b3cc88f015b15df517840d36ac57284

Just copy the file into datacenter/per-user/ai/templates/ 

Argo should rollout the change direct at your running cluster.
