### ISSUE TITLE
Fedora Detection not precise enough 

### ISSUE THREAD

**Issue by nexus-Six** [cloud-native-robotz-hackathon/infrastructure#70]
For the model training, increasing the Samples (2000 is too much for the storage), batches and Epochs increases confidence score, but the coordinates always seem to be off. The square is always at the top of the hat.

  
![image](https://github.com/user-attachments/assets/52173cc4-1924-4b8f-a9eb-cbc23a98896a)

**Comment by rbo** [comment]
Is it really the object detection or the box drawing?

**Comment by nexus-Six** [comment]
The mode is also trained on tennis balls. The coordinates seem to be precise.
![image](https://github.com/user-attachments/assets/b611d5d0-8ad6-491a-bb70-1a93dc5f208e)

**Comment by nexus-Six** [comment]
This an image from the first trainings before the first workshop, perhaps it was always like that
![image](https://github.com/user-attachments/assets/65169ad5-ac11-48ad-af3e-4332a20609b5)

**Comment by nexus-Six** [comment]
Current pipeline default settings provide sufficient detection reliability. Leaving Issue open for some more testing.
