### ISSUE TITLE
Provide a reference DataConnection / Bucket Model as Fallback

### ISSUE THREAD

**Issue by nexus-Six** [cloud-native-robotz-hackathon/infrastructure#90]

**Comment by rbo** [comment]
Tasks:

- [ ] Update to latest OpenShift AI version
- [ ] Provide a fallback

**Comment by rbo** [comment]
Update to OpenShift AI 2.16 do not solve the issue

**Comment by rbo** [comment]
Looks like this is a duplicate #86
